### ISSUE TITLE
Plugin configuration not available in Strapi 3.1.1 and 3.1.2

### ISSUE THREAD

**Issue by niekfrontmen** [boazpoolman/strapi-plugin-sitemap#10]
### Version
Strapi 3.1.1 & 3.1.2

### Steps to reproduce
- Install plugin, delete `build` and `.cache` folders and run `yarn build --clean`
- Clean browser cache

### What is Expected?
The plugin should be listed in the Admin Dashboard

### What is actually happening?
It's not showing so you cannot configure the plugin

<img width="1915" alt="Screenshot 2020-07-30 at 21 15 00" src="https://user-images.githubusercontent.com/35929516/88964621-f205e500-d2a9-11ea-9e89-1a3e7bcfca72.png">
<img width="1913" alt="Screenshot 2020-07-30 at 21 15 17" src="https://user-images.githubusercontent.com/35929516/88964636-f500d580-d2a9-11ea-9b04-02985c7fc581.png">

**Comment by niekfrontmen** [comment]
Thanks!

**Comment by boazpoolman** [comment]
Haha, thank you for your issue submission! I actually fixed this yesterday, but had yet to make a release. Just did. See version [1.1.3](https://www.npmjs.com/package/strapi-plugin-sitemap/v/1.1.3)

**Comment by niekfrontmen** [comment]
Just tested it, works like a charm ;)
Thanks again!
