### ISSUE TITLE
Default locale

### ISSUE THREAD

**Issue by marcospassos** [boazpoolman/strapi-plugin-sitemap#101]
## Bug report

First of all, this plugin is amazing. Thank you for working on this!

### Describe the bug

The current behavior is kind of random - the content type sometimes appears in a locale as default and other times with another. That affects how the pages are ranked.

### Steps to reproduce the behavior

1. Install the plugin
2. Add multiple contents with multiple locales
3. Open the sitemap and  see the default URL is not always in the same locale

### Expected behavior

The content using the default locale should always be used as the default URL.

### Screenshots
Notice that the default URL for the `https://croct.com/blog/pt-br/post/perfil-progressivo` appears as `pt-br` while for `https://croct.com/blog/post/ultimate-guide-ab-testing-analysis` is `en-us` (the correct is en-us, as it's the default locale).

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/943036/204888788-e61fbb31-07b9-4a5b-ba18-d90427e8e774.png">

### System

<img width="906" alt="image" src="https://user-images.githubusercontent.com/943036/204888469-3756e0ad-9671-46b3-876c-938eaa84aab5.png">

**Comment by marcospassos** [comment]
By random, I mean the default URL is decided randomly, not that it changes randomly (e.g., when I refresh the page). Looking at the source code I noticed that the expected behavior isn't explicitly specified:

https://github.com/boazpoolman/strapi-plugin-sitemap/blob/f76085e49f6a5e36e0fcf322267f9e1c6feaddbc/server/services/core.js#L22-L81

More specifically, the `getSitemapPageData` doesn't seem to look up the page by the default locale.

https://github.com/boazpoolman/strapi-plugin-sitemap/blob/f76085e49f6a5e36e0fcf322267f9e1c6feaddbc/server/services/core.js#L92-L128

Aparently, the root cause is that the ID determines the page used as default, so the order in which the content is inserted determines which page is considered default:
https://github.com/boazpoolman/strapi-plugin-sitemap/blob/f76085e49f6a5e36e0fcf322267f9e1c6feaddbc/server/services/core.js#L142-L162

Taking it into account, this is a possible solution for the issue:

- `getSitemapPageData` should retrieve the default locale and check if a page with that locale exists
- If so, pass the URL as the `defaultURL`
- Otherwise, use the current heuristic

**Comment by marcospassos** [comment]
Hey @boazpoolman,any news on this?

**Comment by boazpoolman** [comment]
Hey @marcospassos,

Excuse me for taking this long to get back to you.

About the issue. The implementation is based on my interpretation of [Google's documentation](https://developers.google.com/search/docs/specialty/international/localized-versions#sitemap) about localized sitemaps.

The docs state:
> If you have 3 versions of a page, your sitemap will have entries for the URLs of each version, and each entry will have 3 identical child entries. 

If we consider that, it is not strange at all that you're sitemap contains URLs of different languages.

You mentioned:
> `https://croct.com/blog/pt-br/post/perfil-progressivo` appears as `pt-br` while for `https://croct.com/blog/post/ultimate-guide-ab-testing-analysis` is `en-us`

Though if you look at the rest of you're sitemap, it will contain the translated counterparts for both these URLs.

If I'm missing something here, please let me know.

**Comment by marcospassos** [comment]
Hi @boazpoolman, I think you didn't get my point. Your interpretation is correct. However, let's support we have the following post in 2 languages, `pt-br` and `en-us`:

```
post/ultimate-guide-ab-testing-analysis
```

Because en-us is the default locale, we should have the following entries:

```xml
<url>
    <loc>https://www.example.com/post/ultimate-guide-ab-testing-analysis</loc>
    <xhtml:link
               rel="alternate"
               hreflang="en-us"
               href="https://www.example.com/en-us/post/ultimate-guide-ab-testing-analysis"/>
    <xhtml:link
               rel="alternate"
               hreflang="pt-br"
               href="https://www.example.com/pt-br/post/ultimate-guide-ab-testing-analysis"/>
  </url>
```

Notice that the root has no language in the URL. In case the post has content in the default locale, it should be the `<loc>`. Otherwise, any other locale is available. This is not ensured in the code currently, which makes the main URL unstable and susceptible to SEO penalities.

**Comment by boazpoolman** [comment]
Hi @marcospassos,

I still don't quite follow you on this one. Please help me understand.

You explicitly state that the root has no language in the URL. Are you suggesting that it _should_ work like that?

I'm thinking that the root loc should have _a_ langcode in the URL. Which one doesn't really matter because all languages should have a root item.

I feel like this snippet is correct:

```

<url>
    <loc>https://www.example.com/en-us/post/ultimate-guide-ab-testing-analysis</loc>
    <xhtml:link
               rel="alternate"
               hreflang="en-us"
               href="https://www.example.com/en-us/post/ultimate-guide-ab-testing-analysis"/>
    <xhtml:link
               rel="alternate"
               hreflang="pt-br"
               href="https://www.example.com/pt-br/post/ultimate-guide-ab-testing-analysis"/>
  </url>

```

**Comment by boazpoolman** [comment]
I'm gonna be closing this issue as I'm quite certain the localized sitemaps are implemented correctly.

@marcospassos  If you ever have any more questions, feel free to re-open this issue.
