### ISSUE TITLE
Allow Configuration for Read/Write Directory

### ISSUE THREAD

**Issue by MikeBarberry** [boazpoolman/strapi-plugin-sitemap#106]
Hello 👋 

I'm wondering whether it would be possible to make the write/read directories configurable rather than hard-coded?

We are building for a AWS Lambda deployment and can only write the to /tmp directory. 

With serverless becoming more and more common, maybe others would benefit from this as well?

**Comment by boazpoolman** [comment]
Hi @MikeBarberry,

Thanks for bringing up this issue. I see how this would be usefull, though seeing as the plugin depends on the sitemap file being in the public folder to have it be publicly accesible this is not an easy fix.

I'll schedule some time in Q2 to work on this plugin and I'll be sure to give this issue a look!

**Comment by MikeBarberry** [comment]
Okay, thank you!

**Comment by boazpoolman** [comment]
This feature has been released with [version 3.0.0](https://github.com/boazpoolman/strapi-plugin-sitemap/releases/tag/3.0.0) of the Sitemap plugin.

As of this new version, the plugin serves a "virtual sitemap". This is not a XML file stored in the public folder in your file system. Instead the XML gets saved to the database and an XML API endpoint is exposed to access the sitemap. 
This means that the issue as described above is no longer relevant.
