### ISSUE TITLE
Plugin Admin Page breaks after sitemap.xml is generated

### ISSUE THREAD

**Issue by jaeha-mp** [boazpoolman/strapi-plugin-sitemap#107]
### Describe the bug

After generating sitemap, plugin admin page breaks and shows white page.

When I build strapi, it is built as production thus I could not resolve where the error originated from. 

### Steps to reproduce the behavior

1. install strapi-plugin-sitemap: 2.0.9
2. build strapi
3. run strapi develop 
4. generate sitemap using plugin (any content) with pre generated contents.

### Expected behavior

Plugin admin page(/admin/plugins/sitemap) shows that current xml is loaded.

### System

- Node.js version: node 16.17.1
- NPM version: 8.15.0
- Strapi version: 4.5.2
- Plugin version: 2.0.9 
- Database: PostgreSQL
- Operating system: MacOS Ventura (13.1)

### Additional context

Important note : after downgrading this plugin to 2.0.8, things work properly.

probably these changes are inducing the error. (2.0.8 vs 2.0.9)

https://github.com/boazpoolman/strapi-plugin-sitemap/compare/2.0.8...2.0.9

**Comment by boazpoolman** [comment]
Hi @jaeha-mp,

I'm unable to reproduce this issue.
Is this still a problem for you?

**Comment by boazpoolman** [comment]
I'm gonna close this due to inactivity.

Please feel free to re-open if you're still experiencing this issue.
