### ISSUE TITLE
Relational URLs

### ISSUE THREAD

**Issue by pedrolaxe** [boazpoolman/strapi-plugin-sitemap#113]
Hello its possible create relational urls?
I tried /[category.slug]/[slug] or /[category[slug]]/[slug] but not working...

**Comment by boazpoolman** [comment]
Yeah, this is implemented in the beta. You can install that like 'yarn add strapi-plugin-sitemap@beta'.

Though I'm still not 100% happy with the implementation, so the stable version will have to wait a bit.

**Comment by boazpoolman** [comment]
Yeah, this is implemented in the beta. You can install that like 'yarn add strapi-plugin-sitemap@beta'.

Though I'm still not 100% happy with the implementation, so the stable version will have to wait a bit.

**Comment by pedrolaxe** [comment]
Hey @boazpoolman,
I'm going to install it for now, and I hope it comes out in stable as soon as possible.
Thanks

**Comment by boazpoolman** [comment]
I hope so too
