### ISSUE TITLE
Error with strapi v4.11

### ISSUE THREAD

**Issue by arixwap** [boazpoolman/strapi-plugin-sitemap#114]
### Describe the bug

Error in admin page when you try to edit content type and return to list. Only appear in strapi v4.11

### Steps to reproduce the behavior

1. Install strapi v4.11 or above
2. Install this plugin `npm install strapi-plugin-sitemap`
3. Open admin page, try to add some collection, example user
4. Return to collection list.
5. Error should be appear

### Expected behavior

Screen should be blank white or show error in strapi admin page

### Screenshots

<img width="2240" alt="Screenshot 2023-06-13 at 11 42 29" src="https://github.com/boazpoolman/strapi-plugin-sitemap/assets/11769214/c822420a-a8ae-427b-a444-7eaa184ece2e">

### Code snippets

null

### System

- Node.js v18: (its working well before updated to strapi v4.11)
- NPM version: v9.6.7
- Strapi version: v4.11.1
- Plugin version: latest
- Database: sqlite
- Operating system: MacOS Ventura

### Additional context

cheers up! :)

**Comment by boazpoolman** [comment]
Thanks for reporting this @arixwap.

A fix has been released with `v2.0.11`.

Please let me know if that version solves the problem for you.
