### ISSUE TITLE
Area/Path for collections can not be set individual

### ISSUE THREAD

**Issue by DaTurboD** [boazpoolman/strapi-plugin-sitemap#12]
Each time i am changing the area/path for a collection type it's going to be changed for every other collection also which means i can not set individual areas/paths.
Tried already reinstalling the plugin but it seems like the "config file" isn't removed that way.

**Comment by boazpoolman** [comment]
Thanks @DaTurboD for reporting this issue, I'll look into it tonight 👍

**Comment by DaTurboD** [comment]
Just found out it's still working and generating the right paths, but it isn't showing them on the input fields.
In each input field it shows the value which was last saved.

**Comment by boazpoolman** [comment]
@DaTurboD This should now be fixed in v1.1.4.
https://www.npmjs.com/package/strapi-plugin-sitemap/v/1.1.4
