### ISSUE TITLE
Invalid Date Google Search Console

### ISSUE THREAD

**Issue by QuarkAgency** [boazpoolman/strapi-plugin-sitemap#122]
Hello, I am trying to submit my sitemap to the search console.

![image](https://github.com/boazpoolman/strapi-plugin-sitemap/assets/117939567/6b287f2d-8e10-45f0-b99f-2e937239211a)

The sitemap is valid but google returns me error about invalid date.

Is the date needs to be adapted or is this a Google issue ?

**Comment by boazpoolman** [comment]
Hi @QuarkAgency,

Thanks for submitting this issue.
Does it also say what format it _does_ expect for the lastmod date?

**Comment by QuarkAgency** [comment]
No unfortunately no infos about the expected format :

![image](https://github.com/boazpoolman/strapi-plugin-sitemap/assets/117939567/ed07378e-bb1f-4262-aadb-bbcccbbae01e)

**Comment by boazpoolman** [comment]
Hmm.

I guess we have to "trial-and-error" solve this problem.

Don't know what format it expects

**Comment by QuarkAgency** [comment]
I forgot to mention I am using the version ^2.1.0-beta.0 of the plugin.
I need the new feature to use relation field in page URL

The format is the W3C one :

https://www.w3.org/TR/NOTE-datetime

So this should be the good one. I see on different forums sometimes the Search Console is bugged about sitemap validation

**Comment by boazpoolman** [comment]
Using beta shouldn't affect the lastmod date formatting.

If you're able to verify the format it does expect, I'll be happy to accept a PR. Otherwhise I'll try to look into this when I have the time.

Also please do share sources of information about the google sitemap validation being faulty.

**Comment by boazpoolman** [comment]
Upon investigating it seems to me that the dates in the sitemap comply with ISO 8601.
Meaning they should be valid in a sitemap.xml according to Google.

Might be a bug on Google's side.
Are you still experiencing this issue?

**Comment by boazpoolman** [comment]
I'm gonna be closing this issue as I'm quite certain the lastmod dates are implemented correctly.

@QuarkAgency  If you ever have any more questions, feel free to re-open this issue.
