### ISSUE TITLE
Index.xml don't use hostname

### ISSUE THREAD

**Issue by denisjankovic** [boazpoolman/strapi-plugin-sitemap#127]
Hi there, 
I use the new feautre to split sitamap in multiple parts, all works fine, just when i'm in production index.xml don't use hostname for paths to sitemap parts it use http://localhost:1337 hostname.
Did I do something wrong ? 

![image](https://github.com/boazpoolman/strapi-plugin-sitemap/assets/11853261/bbfb119b-0db8-4ff2-acd9-e4f4c93113ff)

**Comment by boazpoolman** [comment]
Hmm. That seems like a bug. I need to investigate.

**Comment by boazpoolman** [comment]
Could you try setting the `url` in the `config/server.js`?
Docs: https://docs.strapi.io/dev-docs/configurations/server#available-options

**Comment by denisjankovic** [comment]
@boazpoolman Hi, thanks for you backup, that works fine :)

**Comment by boazpoolman** [comment]
Cool. I'll do some more investgation to see if we can do without setting that `url` var.
If not; we have to update the documentation to reflect that.

**Comment by boazpoolman** [comment]
So it turns out that there is a way to fetch the backend URL without explicitly setting it in the `config/server.js`.
I've added [a commit](https://github.com/boazpoolman/strapi-plugin-sitemap/commit/5395e362473d7d4eee80daae49e04c1578b19354) that does just that. I'll make a release shortly.

**Comment by boazpoolman** [comment]
This has been fixed in v3.0.2

**Comment by boazpoolman** [comment]
It turns out that fix that I did in 3.0.2 doesn't work.
I've reverted it in 3.0.3.

As mentioned in this thread we should set the `url` in the `./config/server.js` file.
I've added some documentation about this in the README.

**Comment by faceless49** [comment]
@boazpoolman why did you delete local copy of sitemap in public dir?

**Comment by boazpoolman** [comment]
In v3 I've removed the need of a writable public directory completely by moving the sitemap to the database.
A public XML endpoint is exposed which serves you the sitemap from the database.

Reason being; a lot of issues with writing and reading on different machines which are all fixed by using virtual sitemaps.

**Comment by ilnytskyi** [comment]
I'd consider this as a bug, because in the page, the links use base url overrides. But in index.xml it could be either relative url or custom domain from config overrides as well.

**Comment by boazpoolman** [comment]
@ilnytskyi could you elaborate?
I don’t quite understand.
