### ISSUE TITLE
Update dependencies to mitigate vulnerabilities

### ISSUE THREAD

**Issue by kahrpatrick** [boazpoolman/strapi-plugin-sitemap#130]
### Describe the bug

Several dependencies (e.g. babel) make use of a vulnerable version of the `semver` package. A patched version has been released.

### Steps to reproduce the behavior

1. enable Github Dependabot to get automatic reports
2. or run `npm audit`

**Comment by boazpoolman** [comment]
It took a while for Dependabot to pick up on it, but it did just create a PR #131
