### ISSUE TITLE
how to exclude a specific url for sitemap

### ISSUE THREAD

**Issue by Arunjenson-SurveySparrow** [boazpoolman/strapi-plugin-sitemap#134]
### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: 
- NPM version:
- Strapi version:
- Plugin version:
- Database:
- Operating system:

**Comment by boazpoolman** [comment]
<img width="1006" alt="Scherm­afbeelding 2023-08-01 om 09 25 10" src="https://github.com/boazpoolman/strapi-plugin-sitemap/assets/9551934/2f1e0820-2072-43f6-993a-02f9a7ecdbc3">

**Comment by boazpoolman** [comment]
You're really not giving my much to work with here.
You haven't filled in the issue template and just commented with 3 words..

That checkbox is visible for all pages that are included in the sitemap, regardless of it being published or not.

**Comment by Arunjenson-ss** [comment]
@boazpoolman  so is there any way that  we can automate this stuff , in my case every entry in my  collection type is separate inner page ,so for each page i have a seo component where i have metaRobots field, so if i give some value like "noindex" in that field can we automatically toggle that exclude from sitemap ?

**Comment by boazpoolman** [comment]
A PR is being worked on to implement conditional rules, to include only URLs that match a specific condition. See #109

**Comment by Arunjenson-ss** [comment]
yes please do merge at the earliest

**Comment by boazpoolman** [comment]
As you can see in de PR, it is not yet finished.

**Comment by joelveloso** [comment]
@boazpoolman apologies for jumping in,

quick question, the "Exclude from sitemap" is not showing for me:

![image](https://github.com/boazpoolman/strapi-plugin-sitemap/assets/31883343/504fd92c-4776-4225-84e1-064b47c178ac)


Anything I need to do to enable this feature?

**Comment by boazpoolman** [comment]
@joelveloso 

The checkbox will only show if the entry you're editing is of a type that has a URL bundle configured in the sitemap plugin.
Could you double check that's the case?

**Comment by joelveloso** [comment]
🤦‍♂️

![image](https://github.com/boazpoolman/strapi-plugin-sitemap/assets/31883343/88bd347d-420c-4aa2-8205-90c6bf758021)


thank you
