### ISSUE TITLE
How to combine multiple content-types?

### ISSUE THREAD

**Issue by vatsal-elixir** [boazpoolman/strapi-plugin-sitemap#137]
I have 3 content types

1. Language
2. SubCategory 
3. MediaContent - Relation with language and subcategory

How can I generate sitemap with this pattern   xyz/language.Slug/subcategory.Slug

**Comment by boazpoolman** [comment]
Hi @vatsal-elixir,

Relational patterns were released as a feature with version 3.0.0.

If you're still on version 2.x you'll have to upgrade the plugin.

**Comment by boazpoolman** [comment]
Hope you've made it work @vatsal-elixir.
If you're having trouble upgrading please report a new issue.

I'm gonna close this due to the issue being invalid.
