### ISSUE TITLE
Server.js configuration for the sitemap plugin

### ISSUE THREAD

**Issue by dhimannilesh** [boazpoolman/strapi-plugin-sitemap#138]
Hello,
I have a blog list having more than 50 blogs. As said, the sitemap xml will not show the blogs as they must be created in chunks. 
I think the solution as you mentioned is to update the limits and configure the server.js file. 
What information should I pass to the server.js file? The document is missing that information. We need this to configure our website. All the urls are getting generated except blogs.

**Comment by boazpoolman** [comment]
Hi @dhimannilesh,

Thanks for reporting this issue.
Could you supply some additional information about your environment?
Ideally you would fill in the [issue template](https://github.com/boazpoolman/strapi-plugin-sitemap/blob/master/.github/ISSUE_TEMPLATE/bug_report.md).

What I can say at this point is that I've tested the plugin with 50.000 URLs without any issues, so 50 blogs shouldn't be any problem.

**Comment by dhimannilesh** [comment]
## Bug report

### Describe the bug
Unable to render URLs when it has more than 50 pages.
We have a blog page which contains more than 50 urls of different blogs. As per the plugin, more than 50 urls should be added as chunks. We did the configuration as per the documentation but still unable to generate the blod xmls in the sitemap file


### Steps to reproduce the behavior

1. Installed the sitemap plugin
2. Added the plugin information in plugin.js with limit of 75
 
![image](https://github.com/boazpoolman/strapi-plugin-sitemap/assets/94486745/e6e8f497-aa2f-4f27-b61c-57352d11c30c)
![image](https://github.com/boazpoolman/strapi-plugin-sitemap/assets/94486745/f414934a-35d9-44a4-86f7-1e92be2c466a)

3. Added all the Urls through the URL bundle
4. 
![image](https://github.com/boazpoolman/strapi-plugin-sitemap/assets/94486745/e3dca9be-2b85-46d5-ae9a-601bdf95cbb0)
5. Set Exclude draft to OFF
![image](https://github.com/boazpoolman/strapi-plugin-sitemap/assets/94486745/9300f181-4432-40c2-a63e-116638e06c67)
6. Server.js - Need additional information . No documentation available
### Expected behavior 

Index.xml should render all the urls after generating the sitemap.

### Screenshots

Attached above


### System

- Node.js version: 18.0.0
- NPM version: 6.0.0
- Strapi version: 4.13.1
- Plugin version: 3.0.3
- Database: postgres
- Operating system: Linux and Windows for local testing

### Additional context

Add any other context about the problem here.

**Comment by boazpoolman** [comment]
Just a couple questions to confirm:

1. You're talking about 50 blogs. Or 50.000 blogs?
2. Does the sitemap generation finish succesfully or does it hang indefinetly?

**Comment by dhimannilesh** [comment]
@boazpoolman - 50+ blog which comes under one api   >  /blog/[Slug]. 
I think for that purpose we have to increase the limit field in the plugin.js ?

No, the sitemap generation didn't hang. It just created one index.xml ignoring the 50+ links related to the blogs .

**Comment by dhimannilesh** [comment]
@boazpoolman   Ok .Even after adding back the / . It didn't render the links falling under or blogs category. Pfa the screenshot

![image](https://github.com/boazpoolman/strapi-plugin-sitemap/assets/94486745/ceedce32-3680-49fc-a96a-47547040a18c)

**Comment by boazpoolman** [comment]
Very strange, but thanks for confirming.

Another slightly obvious check; did you save the settings, and hit the generate button in the admin panel before checking the XML file?

**Comment by boazpoolman** [comment]
Allright.

If you're able to send me a (anonymized) database I'd be willing to check it out locally.
Otherwise you'll have to do some debugging yourself.

**Comment by dhimannilesh** [comment]
@boazpoolman I got the root cause . The 'exclude for sitemap' field in content type builder was checked by default. 
Closing this issue. Thank you for the support

**Comment by dhimannilesh** [comment]
@boazpoolman - Does the plugin support image tags ? I have seo model added in my component, but it is not rendering . Any help you can provide ?

**Comment by boazpoolman** [comment]
The plugin does not yet support image sitemaps. If you want to create a feature request issue for that I'll be sure to check it out in the future 🙂
