### ISSUE TITLE
Exclude draft entries from sitemap

### ISSUE THREAD

**Issue by AlexDede** [boazpoolman/strapi-plugin-sitemap#14]
Strapi supports Draft & Publish and will be good if this plugin can exclude all Draft entries from sitemap

**Comment by boazpoolman** [comment]
Thanks @AlexDede for your issue submission.
I've added a new setting to exclude all drafts in v1.2.0
See [https://www.npmjs.com/package/strapi-plugin-sitemap/v/1.2.0](https://www.npmjs.com/package/strapi-plugin-sitemap/v/1.2.0)
