### ISSUE TITLE
Critical dependency: the request of a dependency is an expression

### ISSUE THREAD

**Issue by ainsleyclark** [boazpoolman/strapi-plugin-sitemap#145]
Hi there. There seems to be a dependency issue:

```
WARNING in ../node_modules/strapi-plugin-sitemap/admin/src/index.js 93:66-76
Critical dependency: the request of a dependency is an expression
```

I thought `3.0.6` may solve it but seems to be the same.

### Screenshots

<img width="369" alt="image" src="https://github.com/boazpoolman/strapi-plugin-sitemap/assets/34712954/751eafec-0534-4bfc-9972-a908e256a235">

### System

- Node.js version: v18.18.2
- NPM version: 9.8.1
- Strapi version: 4.15.1
- Plugin version: 3.0.6
- Database: Postgres
- Operating system: macOS

**Comment by boazpoolman** [comment]
Hi @ainsleyclark 

Could you elaborate a bit more?
What version of Strapi are you running? How did you get here?

Ideally you would follow the [Bug report issue template](https://github.com/boazpoolman/strapi-plugin-sitemap/blob/master/.github/ISSUE_TEMPLATE/bug_report.md).

**Comment by ainsleyclark** [comment]
Thanks @boazpoolman I've updated the issue.

**Comment by TMSchipper** [comment]
@ainsleyclark Thanks for mentioning.
What command did you run to end up with this error? 
I just installed the package with your node version and everything is working fine.

**Comment by boazpoolman** [comment]
Hi @ainsleyclark 

It turns out versions `4.15.0` and `4.15.1` contain some issues.
Strapi advises to roll back to version `4.14.6`.
Could you try that version to see if this issue is resolved?

**Comment by ainsleyclark** [comment]
Can confirm `4.14.6` works. Seems to be a vast amount of bugs in the new versions.
Appreciate the help!
