### ISSUE TITLE
Make the <xhtml:link> element in XML optional

### ISSUE THREAD

**Issue by pedrosilva57** [boazpoolman/strapi-plugin-sitemap#155]
### Summary
Currently, the XML returned includes `<xhtml:link>` elements, even with `xsl` option set to false, which causes the browser to display the sitemap as a page with the XML values as its content.

### Why is it needed?

I'm currently using Strapi as the backoffice of a Remix React website, and have the need to create a sitemap on the frontend that displays the sitemap XML from Strapi. Because of this, it is necessary to call the API to get the sitemap XML to then display on the page. But since `<xhtml:link>` elements are included, the browser doesn't display the URLs as an XML file, and instead as a page with the XML values as its content. To display the sitemap correctly, these elements have to be removed programmatically. 

### Suggested solution(s)

Provide an option to configure whether the `<xhtml:link>` elements are included in the sitemap XML.

**Comment by boazpoolman** [comment]
Hi @pedrosilva57

Thanks for submitting this feature request!

Sadly I won't implement this feature as it surpasses the scope of what this plugin is meant to do.
The plugin is simply meant to output an XML sitemap which can be used for better indexation of your website by Google or other search engines.

Alternatively you could use the [Webtools plugin](https://github.com/pluginpal/strapi-webtools) (which I've also created) for your URL management. With that plugin you can add dynamic URLs directly to your Strapi content. Those URLs are then exposed through an API endpoint which you could use to build a dynamic sitemap on the frontend.

Full disclosure; I will eventually move this sitemap plugin to the Webtools suite. The sitemap will then be generated based on those dynamic URLs I mentioned.
