### ISSUE TITLE
Sitemap Breaks When Exceeding Limit and Strapi Port Differs from Default

### ISSUE THREAD

**Issue by 101sam** [boazpoolman/strapi-plugin-sitemap#160]
## Bug report
Sitemap Breaks When Exceeding Limit and Strapi Port Differs from Default

### Describe the bug

Plugin default value:
Limit: 45000 breaks to pages

```
Sitemap URL | Last modification date
-- | --
http://localhost:1337/api/sitemap/index.xml?page=1 |  
http://localhost:1337/api/sitemap/index.xml?page=2 |  
http://localhost:1337/api/sitemap/index.xml?page=3 |  
```
When crossing the limit, the site map is broken. 

### Steps to reproduce the behavior

1. `env` define port `any - not default`
2. `config/plugin.[ts]/[js]` change `limit` to `2` to force creating multi-pages
3. Re-Run Strapi
3. Click on `Generate sitemap`
4. Click [Go to the sitemap]
5. see the error
### Expected behavior

Pointing to: `HTTP[s]://DOMAIN:PORT/api/sitemap/index.xml?page=n`

**However, the preferred results should be (like in our case API server and front end not using the same domain):** 

Instead of using page=n you should use  

In our case, A Full URL 
Pointing to: `http://DOMAIN:4337/api/sitemap/[page]/index.xml`

### Error Screenshots
![image](https://github.com/boazpoolman/strapi-plugin-sitemap/assets/13782917/7ee1601f-32ee-40b2-898f-b6c8be047beb)

### Code snippets
 plugin config

```
---
'sitemap': {
    enabled: true,
    config: {
      cron: '0 0 0 * * *',
      limit: 2,
      xsl: true,
      autoGenerate: false,
      caching: true,
      allowedFields: ['id', 'uid'],
      excludedTypes: [],
    },
  },
---
```
### System

STRAPI VERSION: v4.20.0
Community Edition
NODE VERSION: v20.11.0
"strapi-plugin-sitemap": "^3.0.8",

### Additional context

NA

**Comment by MSACC** [comment]
Let me know if this helps you:

https://github.com/boazpoolman/strapi-plugin-sitemap/issues/83#issuecomment-1120439644

**Comment by 101sam** [comment]
The beta version solves the port issue.

**Comment by boazpoolman** [comment]
Hi @101sam

Which beta version are you currently using now?
This should all have been merged to the stable release by now.

**Comment by boazpoolman** [comment]
Note this part from the readme to make sure the URLs in the index are correct:

> It is required to set the url in the ./config/server.js file in your Strapi installation. That will be used to create the links to the different chunks.
