### ISSUE TITLE
Does not work with Container hosted instances

### ISSUE THREAD

**Issue by tjrexer** [boazpoolman/strapi-plugin-sitemap#25]
@boazpoolman awesome job, really great plugin.  I'm running into a problem with hosting it in a container though.  Most of the plugins for strapi get added to either `/api` or `/extensions`, but this one doesn't.  I suspect that it is saving everything under the local node_modules folder?  This then becomes an issue when packaged since the routes added to save configs don't get packaged, so you can't update once in the container.

Looking for thoughts on how to get around this.  Once I figure that out, I'll be happy to help you add it to the package permanently.

**Comment by boazpoolman** [comment]
Hey @tjrexer!
Thank you for your issue submission.

As you stated; once downloaded this plugin wil be stored in de node_modules folder of you Strapi instance.
Though I'm unsure what you mean by hosting it in a container. Do you mean a docker container? With the strapi/strapi docker image?

Also as far as I'm concerned any community plugin you'd download will be stored in the node_modules folder. Do you also maby have an example of a plugin which does work in your installation.

Thanks in advance! 🙃

**Comment by tjrexer** [comment]
When writing my reply, started to dig a little more into my setup.  Turns out I didn't have nginx set up correctly.  I didn't realize that the plugin added new api paths that needed to be added to proxy settings, thought it worked within the existing `content-manager` paths.

With regards to the `strapi/strapi docker` setup, you are correct, that is what I was referring to.  Storing in `node_modules` isn't what I was referring to though.  Most extensions/plugins have configs that are modified under the `/config` or `/extensions` directory in the project.  However, since there aren't any settings for this plugin there, you need to import the full `./build/` directory from outside the container.

Best practice for docker is to import configs/files, & rebuild a clean copy inside the container.  However, since I don't see anything for the plugin I don't believe it's being imported correctly.  That is why I suspect that the settings or changes are being stored locally for the plugin in `node_modules`, but it could also be in `.cache` (another file not imported).

**Comment by boazpoolman** [comment]
Ah allright, I think I get the issue.

To answer your question: the settings of this plugin are stored in de `core_store` table of your database.
The contents of this table can not be migrated across environments by default in Strapi.
So you would manually have to do the changes in the admin UI again in your docker env, or copy the contents of the `core_store` table and paste them in the database of your docker.

Another option for this is using my other strapi plugin [strapi-plugin-config-sync](https://www.github.com/boazpoolman/strapi-plugin-config-sync).
This plugin allows you to export all the values from the `core_store` table and write them as json files in the `/extensions` folder of you project.
With the values persisted as files you can migrate to another environment en import all these files to overwrite your database with the new values.
This plugin is still in development, but it should do the trick.

Let me know if this clears it up for you!

**Comment by tjrexer** [comment]
Yea, it does, thanks.  I only have one environment, so the `core_store` table works for me, but would probably be good to add information about both the NGINX config & your `config-sync` plugin to the README in case anyone else runs into the same problem.  Might be good to cover it as an advanced setup.
