### ISSUE TITLE
Tutorial video is broken

### ISSUE THREAD

**Issue by filipesmedeiros** [boazpoolman/strapi-plugin-sitemap#3]
Hey! I'm very interested in this, would it be possible to make the video available? Thanks!

**Comment by boazpoolman** [comment]
Hi @filipesmedeiros, the video has been fixed. Thank you for your issue submission :)

**Comment by SubZtep** [comment]
Is the video link still available somewhere?

**Comment by boazpoolman** [comment]
@SubZtep it’s not. I’ve removed it completely to save on package size a while back.

If you want I can help you set up the plugin.

**Comment by SubZtep** [comment]
> 

No thanks, it's fine, I just couldn't find the generated XMLs, but it's sorted.
