### ISSUE TITLE
Unable to generate sitemap when collection names have a space

### ISSUE THREAD

**Issue by skemp42** [boazpoolman/strapi-plugin-sitemap#4]
I am currently unable to generate the sitemap if my collection name has a space (We have done this for it to be human readable on the CMS itsself, annoyingly strapi does not allow for seperate display and data names..)

This is an example of a collection model that does not work:

`{
  "kind": "collectionType",
  "connection": "default",
  "collectionName": "help_article",
  "info": {
    "name": "Help Article"
  },
  "options": {
    "increments": true,
    "timestamps": true
  },
  "attributes": {
    "Url slug": {
      "type": "string"
    },
    "Article title": {
      "type": "string"
    },
    "Image": {
      "model": "file",
      "via": "related",
      "plugin": "upload"
    },
    "Sub title": {
      "type": "string"
    },
    "Blurb": {
      "type": "string"
    },
    "Content": {
      "type": "richtext"
    },
    "Page title (head tag)": {
      "type": "string"
    },
    "Page description (head tag)": {
      "type": "string"
    }
  }
}
`

We believe it blows up on [this line](https://github.com/boazpoolman/strapi-plugin-sitemap/blob/master/services/Sitemap.js#L107)

Thanks for any help on this!

**Comment by mattwcole** [comment]
I was able to fix this by looking up the model name of the content type before querying strapi. [Change here](https://github.com/boazpoolman/strapi-plugin-sitemap/compare/master...mattwcole:content-type-names) - let me know if you want me to put up a PR.

**Comment by boazpoolman** [comment]
Thanks @mattwcole, your fix seems to work. Though the real issue here is that the collection name gets stored in the settings instead of the model name. I've fixed this in the front- and back-end, and used your fix for backward compatibility. See PR.
