### ISSUE TITLE
404 when trying to access the settings

### ISSUE THREAD

**Issue by marieqg** [boazpoolman/strapi-plugin-sitemap#45]
Hello, 
First time I'm using the plugin and I'm struggling with it. 
I have a 404 when I try to go to the plugin settings 

<img width="1559" alt="Capture d’écran 2021-11-20 à 11 16 51" src="https://user-images.githubusercontent.com/48214496/142722885-61432b8a-457e-4fc6-9767-79a752febd74.png">

I'm using an old version of strapi :     "strapi": "3.0.0-beta.20",
Not sure it's supported ? 

Also not sure how to generate the site map once you added settings. I used postman and the routes to populate my settings (not sure it's correct, and the hostname is not populating).
<img width="449" alt="Capture d’écran 2021-11-20 à 11 29 18" src="https://user-images.githubusercontent.com/48214496/142723065-63b12801-c1e5-4c98-8fdc-7ed467c42b3e.png">
<img width="449" alt="Capture d’écran 2021-11-20 à 11 29 26" src="https://user-images.githubusercontent.com/48214496/142723070-9175bb42-1fd3-4ec7-bb7b-fca895928669.png">

Thanks in advance, 
Marie

**Comment by boazpoolman** [comment]
Hi @marieqg,
The latest version of this plugin (1.2.5) supports Strapi 3.4.0 and higher.

I would recommend updating to the latest version of Strapi (3.6.8) not only for this plugin but also to future proof your application!

If you don't want to do that you could manually change the settings in your database. These are located in the core_store table of your database with the key sitemap_plugin_settings. Should be a little bit easier then changing the settings with postman.

**Comment by marieqg** [comment]
@boazpoolman , thanks for your reply. I was also thinking it was a version project. I know I should update to the last version, but I've already spent a lot of extra time the project and not sure I can spend more on the version change. 
Thing is everything in my database seems to be ok and I'm still not generating the sitemap
<img width="1004" alt="Capture d’écran 2021-11-20 à 12 54 10" src="https://user-images.githubusercontent.com/48214496/142725409-57305250-03d5-4c02-89fa-49d9969f6108.png">
:

**Comment by boazpoolman** [comment]
Yeah those are the settings!
If you configure the contentTypes like you had here: https://user-images.githubusercontent.com/48214496/142723070-9175bb42-1fd3-4ec7-bb7b-fca895928669.png and set the hostname of your website I think you might be able to generate the sitemap by calling the service manually
