### ISSUE TITLE
add trailing slash

### ISSUE THREAD

**Issue by Nik96i** [boazpoolman/strapi-plugin-sitemap#47]
hi, I want to add a trailing slash at the end of my routes. 
how can I do that? thanks.

**Comment by boazpoolman** [comment]
Hi @Nik96i,
Why would you want to add a trailing slash?

**Comment by Nik96i** [comment]
my website use trailing slashes. and if I use non-slash URLs all URLs would be redirected with 301 to slash version.

**Comment by boazpoolman** [comment]
Allright, seems like a fair suggestion.
I'll allow using trailing slashes in the pattern of a URL bundle.
Will be released with v2.0.0 of the plugin :)

**Comment by boazpoolman** [comment]
Released in [v2.0.0](https://github.com/boazpoolman/strapi-plugin-sitemap/releases/tag/2.0.0) for the Strapi v4 version of `strapi-plugin-sitemap`.
