### ISSUE TITLE
Throws error when i18n plugin is not installed

### ISSUE THREAD

**Issue by pr0gr8mm3r** [boazpoolman/strapi-plugin-sitemap#54]
### Describe the bug

If I don't have the i18n plugin installed, the sitemap plugin throws the following error when I access the plugin page in the admin panel:
```
error: Model plugin::i18n.locale not found
```

### Steps to reproduce the behavior

1. Setup a strapi instance without i18n plugin installed
2. Navigate to the sitemap settings
3. See error banner pop up and notice error in console output.

### Expected behavior

No error is thrown, missing i18n plugin is ignored.

Even better would be, if the plugin just hid all the i18n-related settings. Just a nice to have.

### System

(Shouldn't matter)

- Node.js version: v14.18.2
- NPM version: 6.14.15
- Strapi version: 4.0.0
- Plugin version: 2.0.0
- Database: sqlite
- Operating system: Linux

**Comment by boazpoolman** [comment]
Thanks for the issue submission!
Fixed in `v2.0.1`

**Comment by pr0gr8mm3r** [comment]
Wow, that was quick. Thanks!
