### ISSUE TITLE
Go to the Sitemap navigates to Localhost instead domain server

### ISSUE THREAD

**Issue by drmayor2004** [boazpoolman/strapi-plugin-sitemap#59]
### Describe the bug
The Go to the Sitemap navigate to http://localhost:4000/sitemap/index.xml instead of the live domain

### Steps to reproduce the behavior

1. Go to 'Strapi Admin'
2. Click on 'Sitemap'
3. Click on 'Go to the Sitemap'
3. New Window is opened
4. Page navigates to http://localhost:4000/sitemap/index.xml

### Expected behaviour
The page should be navigated to https://admin.cgafrica.com/sitemap/index.xml

### Code snippets

If applicable, add code samples to help explain your problem.

### System

- Node.js version: 
- NPM version: 6.0.0
- Strapi version: 4.03
- Plugin version:2.0.4
- Database: sql
- Operating system:

**Comment by boazpoolman** [comment]
Hey @drmayor2004,

Thank you for the issue submission!

I was just wondering; have you specified the domain `admin.cgafrica.com` somewhere in Strapi?
Or is it specified at the server level? In a Apache, or Ngnix proxy.

**Comment by drmayor2004** [comment]
> Hey @drmayor2004,
> 
> Thank you for the issue submission!
> 
> I was just wondering; have you specified the domain `admin.cgafrica.com` somewhere in Strapi? Or is it specified at the server level? In a Apache, or Ngnix proxy.

it is specified at the server level

**Comment by drmayor2004** [comment]
Just deployed the update in live mode and tested it. Issue resolved

**Comment by boazpoolman** [comment]
Great :)
