### ISSUE TITLE
Support URLs containing slashes

### ISSUE THREAD

**Issue by mattwcole** [boazpoolman/strapi-plugin-sitemap#6]
Currently the plugin assumes that all Strapi pages are at the root of the site. URLs like `https://my-site.com/articles/my-strapi-article-1` are not supported because the UID field used in the sitemap doesn't allow slashes. Custom entries have the same problem. I had a go at a solution [here](https://github.com/mattwcole/strapi-plugin-sitemap/commit/ac03b821ff1e106fb44aaa603c9aa059de35d4e4) that adds an `area` property to the settings for both custom and collection entries. Let me know what you think.

![image](https://user-images.githubusercontent.com/6730646/85701741-9dcd7b00-b6d5-11ea-8888-f260668b50ba.png)

**Comment by boazpoolman** [comment]
This looks great. I was kind of hoping that this 'prefix' feature would be added to the UID field type directly. Nonetheless this adds a lot of value to the plugin. I'll test it out. Could you create a PR?

**Comment by mattwcole** [comment]
Agreed it would be more useful to allow this in UID field. I've put up a PR, feel free to amend as needed.

**Comment by boazpoolman** [comment]
I made a couple of changes, most primarily:
- The regex for the custom entry slug field allows '/', which makes the area field here redundant.
- The area field is now an InputUID component (just like slug) to prevent incorrect input.
See https://github.com/boazpoolman/strapi-plugin-sitemap/pull/9

**Comment by mattwcole** [comment]
Nice job, thanks for fixing. The only issue I see with making the area field a UID too is if a URL path needs multiple slashes eg `https://my-site.com/articles/help/my-strapi-help-article1` (probably more likely for custom entries). Not my use case though, so this fix should unblock us.

**Comment by boazpoolman** [comment]
That should not be an issue anymore because I've altered the regex of the UID field to allow slashes.
That said: I want to add a couple more things before making a new release to npm. Next release will likely be somewhere at the start of next week.

**Comment by boazpoolman** [comment]
Fixed in v1.1.2 (https://github.com/boazpoolman/strapi-plugin-sitemap/releases/tag/1.1.2)
Thanks for the work :)
