### ISSUE TITLE
Feature request: an ability to exclude last modification date from generated sitemap

### ISSUE THREAD

**Issue by AlexDede** [boazpoolman/strapi-plugin-sitemap#61]
### Summary

Can you and a new option to `URL bundles` to exclude last modification date for collections.

### Why is it needed?

We have a pages on website that receive part of data from Strapi CMS and another part from our own API. In our case last modification date in  Strapi CMS is incorrect because our API updates data more frequently and we want to exclude last modification date from sitemap for this pages.

**Comment by boazpoolman** [comment]
Hey @AlexDede

Thank you for the feature request.

Seems like a valid suggestion. I'll implement this.

**Comment by Sgubela** [comment]
@boazpoolman Can you give us update about this feature?

**Comment by boazpoolman** [comment]
@Sgubela the update I can give is that I will implement this. It’s still a couple weeks out due to the lack of time I have for this project.

My best guess would be, by the end of the month.

**Comment by boazpoolman** [comment]
I've added a checkbox with which you can opt-out of the lastmod.
It is true by default and can be unchecked to exclude the lastmod from the sitemap.

<img width="922" alt="Schermafbeelding 2022-04-05 om 21 41 08" src="https://user-images.githubusercontent.com/9551934/161839875-664ef04d-f5d9-449c-b0eb-6f12e658de9a.png">

Released with [v2.0.7](https://github.com/boazpoolman/strapi-plugin-sitemap/releases/tag/2.0.7)
