### ISSUE TITLE
not able to add more field types to the allowedFields in config/plugins.js

### ISSUE THREAD

**Issue by jkaplanis** [boazpoolman/strapi-plugin-sitemap#62]
### Describe the bug

I am trying to add the 'text' field type to allowedFields, by adding 'text' to the allowed fields array in config/plugins.js. however the UI in Strapi does not update to make 'text' fields available in the dropdown. 

### Steps to reproduce the behavior

1. Add the below code to config/plugins.js
`module.exports = ({ env }) => ({
  sitemap: {
    enabled: true,
    config: {
      autoGenerate: true,
      allowedFields: ['id', 'uid', 'text'],
      excludedTypes: [],
    }
  }
})`
2. Open Strapi dashboard
3. Under 'Plugins', click 'Sitemap'
4. Add or edit an existing collection that has a text field type
5. Under UID Field, note that 'text' field types are not available

### Expected behavior

After adding 'text' to the allowedFields array in the config/plugins.js file I would expect this field to be available in the UID Field dropdown in Strapi. 

### Code snippets

`module.exports = ({ env }) => ({
  sitemap: {
    enabled: true,
    config: {
      autoGenerate: true,
      allowedFields: ['id', 'uid', 'text'],
      excludedTypes: [],
    }
  }
})`

### System

- Node.js version: 12.21.0
- NPM version: 6.14.11
- Strapi version: 3.6.1
- Plugin version: 1.2.5
- Database: mysql 2.18.1
- Operating system: MacOS Monterey

**Comment by boazpoolman** [comment]
Hey @jkaplanis,

Thanks for the bug report. I’ll do some testing with this.

**Comment by boazpoolman** [comment]
Hey @jkaplanis,

Just noticed the version numbers in the issue. You’re using plugin v1.2.5 for Strapi v3.

The allowedFields config was introduced with plugin version 2.0.0 for Strapi v4.

Please refer to the node_modules/strapi-plugin-sitemap/README.md file in your project for the documentation of the plugin version you’re using.
