### ISSUE TITLE
Feature Request: Add support for sitemapindex

### ISSUE THREAD

**Issue by laurent-malvert-freelance** [boazpoolman/strapi-plugin-sitemap#66]
### Summary

Please add support for the `sitemapindex`.

### Why is it needed?

We generally split our sitemaps using a global sitemap index, which loads the site's sub-sitemaps.

This makes it easier to request a re-indexing from search engines, and allows to combine the sitemap of a global site from different sub-site. 

### Suggested solution(s)

For instance, instead of the existing custom URLs, a separate front-end could generate its own routes-based sitemap, and in Strapi we could request the inclusion of this specific sitemap.

### Related issue(s)/PR(s)

N/A

**Comment by boazpoolman** [comment]
Hi @laurent-malvert-freelance,

Thank you for the excellent feature request.

To implement this I think the plugin will need a big rewrite.
As of now you can only create one sitemap.
To implement this you have to be able to create multiple sitemaps.
Then those sitemaps should be able to be added to sitemap indexes.

When I have the time I'll make the efforts to build this.

**Comment by timnolte** [comment]
Seems like this should just be the default when adding URL Bundles, essentially WordPress does this same sort of thing by default for every custom post type. There is nothing wrong with having the system automatically create a sitemap for each bundle with the main sitemap being the index.

**Comment by boazpoolman** [comment]
This feature was released with [version 3.0.0](https://github.com/boazpoolman/strapi-plugin-sitemap/releases/tag/3.0.0) of the Sitemap plugin.

A sitemap index will automatically be created for sitemaps that contain more URLs than [the limit](https://github.com/boazpoolman/strapi-plugin-sitemap#limit).
