### ISSUE TITLE
Remove filter by `published_at` if `Exclude drafts: false` to properly works on collections with turned off Draft/Publish

### ISSUE THREAD

**Issue by krabbi** [boazpoolman/strapi-plugin-sitemap#69]
### Steps to reproduce the behavior

1) Create a collection with turned off Draft/Publish system on collection.
2) Try to generate sitemap on that collection

### Expected behavior

Sitemap is generated

### Actual behavior

Error in console
<img width="1272" alt="image" src="https://user-images.githubusercontent.com/5084613/154857519-77d49664-65f7-48a6-a834-a2e3e8dddc12.png">

### System

- Strapi version: 4.1.0
- Plugin version: 2.0.6
- Database: Postgres

### Additional context

If remove filter by `published_at` in core services - works fine. So suggested solution is to check for `Exclude drafts` config set to `false` and then not filter by `published_at`

**Comment by boazpoolman** [comment]
Thanks for reporting @krabbi!

I’ll write up te fix.

**Comment by oberkayb** [comment]
yes i have the same problem if you could check it would be great 🎈

**Comment by boazpoolman** [comment]
Released with [v2.0.7](https://github.com/boazpoolman/strapi-plugin-sitemap/releases/tag/2.0.7)
