### ISSUE TITLE
Unable to add to allowedFields

### ISSUE THREAD

**Issue by leonlovett** [boazpoolman/strapi-plugin-sitemap#70]
***
Edit: I have figured out most of it. I was overlooking that we add the data TYPE to allowed fields, instead of the field names. So now I have the fields available in the settings UI.

The only issue that I am seeing now is there is a many -to-one relation field that (this content type is the "one" part of the relation). The value is not showing in the sitemap, even though everything appears fine in the UI.

Edit 2: After digging through the source code, it appears that relation fields aren't supported. Closing this issue.
***

I am trying to use this plugin to generate a sitemap and am having an issue when trying to add some fields in the `allowedFields` section of config.

In `config/plugins.js`, I have added the following:
```
module.exports = {
    sitemap: {
      enabled: true,
      config: {
        autoGenerate: true,
        allowedFields: ['id', 'title']
      }
    }
}
```

Then when I attempt to add a new url bundle using the sitemap settings, I get the following error:

![image](https://user-images.githubusercontent.com/8462457/156285982-2633da38-10e8-4294-8708-53f76c7964f4.png)

The only field that seems to work is "id". I don't know what I am missing here.

Any guidance would be appreciated.

Node version 16.13.0
Strapi plugin sitemap: 2.0.6
Strapi: 4.0.7
NPM : 8.1.3
OS: Windows 11
DB: sqlite

**Comment by boazpoolman** [comment]
Hey @leonlovett,

Did you figure it out?

**Comment by leonlovett** [comment]
Hey @boazpoolman 

Thanks for responding. I did figure out most of it except for the relation field. I just removed that field from my application URL for now.
