### ISSUE TITLE
Pattern contains forbidden fields

### ISSUE THREAD

**Issue by SoftCreatR** [boazpoolman/strapi-plugin-sitemap#71]
Same issue as in #62 

Strapi version: 4.1.2
Plugin version: 2.0.6

Configuration:

```js
sitemap: {
    enabled: true,
    allowedFields: [
      'id',
      'uid',
      'text'
    ],
},
```

However, it only suggests the `id` field, and when trying to use something else, an error message pops up, saying "Pattern contains forbidden fields":

![image](https://user-images.githubusercontent.com/81188/156882880-9945f656-b20f-4f43-958d-1348432e597a.png)
![image](https://user-images.githubusercontent.com/81188/156882891-248a3e89-e23b-44db-85e1-57efdbae1989.png)

I am trying to combine this plugin with that one: https://github.com/ComfortablyCoding/strapi-plugin-slugify

**Comment by boazpoolman** [comment]
Hi @SoftCreatR 

That indeed does seem strange.
Can you confirm that your `Article` CT actually has one or more fields of the `uid` or `text` type?

Maby send paste the schema.json of the CT here.

**Comment by SoftCreatR** [comment]
```json
{
  "kind": "collectionType",
  "collectionName": "articles",
  "info": {
    "singularName": "article",
    "pluralName": "articles",
    "displayName": "Neuigkeiten",
    "description": ""
  },
  "options": {
    "draftAndPublish": true
  },
  "pluginOptions": {},
  "attributes": {
    "title": {
      "type": "string",
      "required": true
    },
    "image": {
      "type": "media",
      "multiple": false,
      "required": false,
      "allowedTypes": [
        "images"
      ]
    },
    "intro": {
      "type": "richtext"
    },
    "content": {
      "type": "richtext",
      "required": true
    },
    "slug": {
      "type": "string",
      "unique": true
    }
  }
}
```

I also tried `string` instead of `text`, but no success.

**Comment by boazpoolman** [comment]
Hmm, in this case `string` would indeed be the correct type to add.

And just to confirm; after you added the plugin config `allowedFields` you restarted your Strapi instance?

**Comment by SoftCreatR** [comment]
Multiple times since then :) I even re-built and restarted it, before answering here.

**Comment by boazpoolman** [comment]
Allright! Thanks for the additional info.

I'll mark this issue as `bug`.
As soon as I plan some time to work on the plugin I'll be sure to pick this up!

**Comment by SoftCreatR** [comment]
Follow up: Just checked the network tab in the browser, and this is what I found:

GET /sitemap/pattern/allowed-fields/

```
{
    "admin::permission": [
        "id"
    ],
    "admin::user": [
        "id"
    ],
    "admin::role": [
        "id"
    ],
    "admin::api-token": [
        "id"
    ],
    "plugin::upload.file": [
        "id"
    ],
    "plugin::i18n.locale": [
        "id"
    ],
    "plugin::users-permissions.permission": [
        "id"
    ],
    "plugin::users-permissions.role": [
        "id"
    ],
    "plugin::users-permissions.user": [
        "id"
    ],
    "api::article.article": [
        "id"
    ],
    "api::company.company": [
        "id"
    ],
    "api::contact.contact": [
        "id"
    ],
    "api::footer.footer": [
        "id"
    ],
    "api::gallery.gallery": [
        "id"
    ],
    "api::homepage.homepage": [
        "id"
    ],
    "api::imprint.imprint": [
        "id"
    ],
    "api::job.job": [
        "id"
    ],
    "api::opening-time.opening-time": [
        "id"
    ],
    "api::privacy-policy.privacy-policy": [
        "id"
    ]
}
```

**Comment by boazpoolman** [comment]
Allright. So while we're getting technical; that request is hooked up to this service:
https://github.com/boazpoolman/strapi-plugin-sitemap/blob/master/server/services/pattern.js#L14

You could try and debug that file in the `node_modules` folder of your project.
Try logging the config, or the content type. Maby you can find the bug 🤷

**Comment by SoftCreatR** [comment]
`strapi.config.get('plugin.sitemap.allowedFields')` doesn't seem to use the settings in `config/plugins.js` but the settings from the [default config](https://github.com/boazpoolman/strapi-plugin-sitemap/blob/master/server/config.js).

**Comment by boazpoolman** [comment]
Ah! I see it.

Your config:

```
sitemap: {
    enabled: true,
    allowedFields: [
      'id',
      'uid',
      'text'
    ],
},
```

Which should be:

```
sitemap: {
    enabled: true,
    config: {
        allowedFields: [
          'id',
          'uid',
          'text'
        ],
    }
},
```

**Comment by SoftCreatR** [comment]
Meh... I should read better 😄 Thank you very much, it works now (after changing `text` to `string` ^^)

Just wondering: Wouldn't it be easier/more intuitive to use the field names, instead of their types?

**Comment by boazpoolman** [comment]
@SoftCreatR great!

Field names would maby be more intuitive, but it's not very scalable.
Right now you can use the plugin without setting any config by using fields of type `uid` or `id`.
If you have to set the field names that would be an extra installation step before you can use the plugin.
Because field names are variable.

**Comment by SoftCreatR** [comment]
But Id and UID (as names) are available by default, aren't they? At least the Id field exists on every object, from what I can tell.

**Comment by boazpoolman** [comment]
`id` and `uid` are available _as types_ by default.
But a `uid` field named "my-weird-url-field-name" would not be available by default if I were to use the field names instead of field types.

The `id` is kind of an exception, because the user can't name the `id` field themselfs.
