### ISSUE TITLE
Surgical URL injection / Caching

### ISSUE THREAD

**Issue by boazpoolman** [boazpoolman/strapi-plugin-sitemap#80]
### Summary

When you have the `autoGenerate` setting enabled and you update a piece of content, all the pages that should be included in the sitemap are queried and afterwards added to the sitemap. If you have a larger sitemap is could be a big performance issue.

### Why is it needed?

It is probably best to only update the URL of the page you have just created, edited or deleted. So only that page will be queried. We can do this by implementing some kind of caching layer.

### Suggested solution(s)

**Solution 1:**
Create a `urls.json` file in which you store al the URLs of the sitemap.
You could surgically add, edit or remove URLs from this file and afterwards regenerate the sitemap.xml based on that JSON file.

**Solution 2:**
Instead of having an extra JSON file that holds the URLs, we could (maby) also just read the URLs from the sitemap.xml file itself and use those to then again regenerate the sitemap.

**Comment by maksymenkoml** [comment]
+1
When we have more than 1000+ items in a sitemap, saving any other item takes 5+ seconds. Also, it generates separate SQL queries for each item, generating 1000+ SQL queries (yes, for each entity save).

**Comment by boazpoolman** [comment]
This feature was released with [version 3.0.0](https://github.com/boazpoolman/strapi-plugin-sitemap/releases/tag/3.0.0) of the Sitemap plugin.

When using the[ auto generate setting](https://github.com/boazpoolman/strapi-plugin-sitemap#auto-generate) you will get better performance due to [a caching layer](https://github.com/boazpoolman/strapi-plugin-sitemap#caching) that caches all the unchanged URLs when updating a single URL.
