### ISSUE TITLE
Clearer explanation of the Allowed fields

### ISSUE THREAD

**Issue by Henrixounez** [boazpoolman/strapi-plugin-sitemap#82]
### Summary

A clearer explanation of the Allowed fields in the Readme to explain that it is the type of the fields and not the field names

### Why is it needed?

At first I thought that this field was an array of the fields names instead of being their types, so I filled with the names that I wanted for the sitemap to be generated with.
When it didn't work, I searched through the source code to understand why it doesn't work and found it that this array was instead a list of types to be included.

### Suggested solution(s)

Make it clearer that it is a list of types. I know that it is said that way in the Readme, but it is not very clear what it is.
Maybe include an example of an array that is not only ["id", "uid"], but also something like ["id", "string"].

Sorry if this feels a bit much, but I was almost being discouraged of using this plugin as I thought that there was a bug inside.

**Comment by boazpoolman** [comment]
Hey @Henrixounez,

You’re not alone in this.
I’ve had several people contact me through GH but also discord because they couldn’t make it work.

Couple things came to my mind to improve on this.

- Also allow fields of which it’s name is in the settings array. Basicly check for both type and name.
- Rename the setting to `allowedFieldTypes`.
- Better documentation in the README (as you suggested)

What do you think you would have been most helped with?

**Comment by Henrixounez** [comment]
Hello @boazpoolman ,

Thank you for telling me that I'm not alone in having this problem, and I have to add that your plugin works extremely well when correctly configured ;)

On your improvement suggestions, the third one would be the best one short term. Explaining in more details or having a disclaimer indicating very obviously that it is indeed the types and not the names of the fields.

Then, longer term I think that the first suggestion might be good, but it depends on your vision whether or not you think it is a good idea to search by name instead of types. Personally I think it is a good idea as, for my example I don't need every "string" type fields to make my dynamic URLs.

The second suggestion might not be needed if at least one of the other two are implemented. Changing the name is also a breaking change for those who already used it (and understood correctly how to use it).

I hope it helps you in improving this small problem.

**Comment by boazpoolman** [comment]
Hi @Henrixounez,

Thanks for the follow-up.

I've gone with the first solution; allowing _both_ field **types** and field **names** to be set in the `allowedFields` setting.
Don't see a reason why not to do it like this. [See commit](https://github.com/boazpoolman/strapi-plugin-sitemap/commit/bc731696ad90462e9112a0f5500e2b6746d3a100).

**Comment by boazpoolman** [comment]
Was released with `v2.0.8` :)
