### ISSUE TITLE
Relational URL pattern

### ISSUE THREAD

**Issue by boazpoolman** [boazpoolman/strapi-plugin-sitemap#86]
### Summary

Allow querying relational fields in the URL pattern like `/prefix/[relation.slug_field]`.

### Why is it needed?
For better dynamic URL patterns.

### Related issue(s)/PR(s)

#75

**Comment by Alexnortung** [comment]
Is it possible to make the population of relational fields recursive for example `/prefix/[relation.relation.slug_field]/[relation.slug_field]/[slug_field]`.

Also a feature for making deeply nested routes would be cool, such as `/prefix/[relation.slug_field*]/[slug_field]`, which would probably also require recusively populating fields.

Thanks for all the hard work you have put into this plugin already!

**Comment by boazpoolman** [comment]
Yeah, making it recursive makes sense to me. Making it possible for you to go infinitely deep with the relation nesting.

Though this syntax I don't get `/prefix/[relation.slug_field*]/[slug_field]`.
What exactly are you querying with the `*` character?

**Comment by quiloos39** [comment]
Any updates on this?

**Comment by boazpoolman** [comment]
The feature is in beta. You can install it like this:

yarn add strapi-plugin-sitemap@beta
or
npm install strapi-plugin-sitemap@beta

**Comment by thibaultcarlier** [comment]
Thank for this feature ! 

We can't do the same with a component relation ?

**Comment by TheRealFlyingCoder** [comment]
@boazpoolman I just realised this must be what @thibaultcarlier must have meant from that comment.

I assumed they meant a component inside of a relation.

Right now if you have a Component on an object you can't reference any fields inside, essentially only root fields are accessible.

**Comment by thibaultcarlier** [comment]
> @boazpoolman I just realised this must be what @thibaultcarlier must have meant from that comment.

Yes exactly, and I noticed that you can't make it link to components. But I find it sad :/

**Comment by TheRealFlyingCoder** [comment]
Yeah @boazpoolman  has suggested this is how it **should** work, so hopefully we will see an update soon to patch this, as the relation update is still in beta :)

**Comment by thibaultcarlier** [comment]
Good news ! Thank for your work !

**Comment by TheRealFlyingCoder** [comment]
@boazpoolman Just bumping this, any chance we can see this update move forward for components?

**Comment by TheRealFlyingCoder** [comment]
Hey @boazpoolman are you still looking to implement the update here for components?

**Comment by boazpoolman** [comment]
I have planned to work on the beta in Q2 of this year. I'll be sure to look at the components relations as wel.

Up until that moment you are free to fork the beta branch and work on this yourself.

**Comment by TheRealFlyingCoder** [comment]
> I have planned to work on the beta in Q2 of this year.

Awesome that's what I needed to know, it means i'll have to find an alternative solution in the mean time but that's fine :)

Thanks!

**Comment by boazpoolman** [comment]
I've opened a PR (#123) that adds the ability to use component fields in the URL pattern.

**Comment by TheRealFlyingCoder** [comment]
Legend 👍

**Comment by boazpoolman** [comment]
This feature has been released with [version 3.0.0](https://github.com/boazpoolman/strapi-plugin-sitemap/releases/tag/3.0.0) of the Sitemap plugin.

You are now able to use relational fields in your URL pattern. Like so: `/pages/[category.slug]/[slug]`
