### ISSUE TITLE
Using no prefix (`/[slug]`) resolve to broken url

### ISSUE THREAD

**Issue by stafyniaksacha** [boazpoolman/strapi-plugin-sitemap#91]
### Describe the bug

When we use a pattern like `/[uri]` which can contain `/`, the resolved url does not contain the hostname

### Steps to reproduce the behavior

1. Go to http://127.0.0.1:1337/admin/plugins/sitemap
2. Add a URL Bundle with a pattern like `/[uri]`
3. Set a hostname in settings like `http://localhost:3000/` (or `http://localhost:3000`)
4. Save
5. Create an entity with `/foo/bar` as `uri`
6. Generate sitemap

### Expected behavior

The url should contain the hostname 

### Screenshots

<img width="341" alt="image" src="https://user-images.githubusercontent.com/3911343/175772412-b62097fc-b6ec-422d-b048-9d343ad7c30a.png">

### Additional context

Adding any string in the pattern before the brackets like `/foo/[slug]` or `/foo/bar/[id]` works

**Comment by stafyniaksacha** [comment]
Solved: using `[uri]` instead of `/[uri]` works like a charm!

**Comment by boazpoolman** [comment]
Hmmm strange issue. But I’m glad you found a workaround 😄
