### ISSUE TITLE
Generate sitemap when server boots

### ISSUE THREAD

**Issue by TriPSs** [boazpoolman/strapi-plugin-sitemap#92]
### Summary

To generate a sitemap when the server boots

### Why is it needed?

We run Strapi in Google Cloud Run, these scale to zero so now sometimes when we retrieve the sitemap it does not exist, creating one on boot would solve this.

### Suggested solution(s)

When the server boots to also create an sitemap.

### Related issue(s)/PR(s)

#84

**Comment by boazpoolman** [comment]
Hmmm, interesting feature request.
You could actually do this yourself aswell.

Just put this code in your bootstrap function:

```
strapi.plugin('sitemap').service('core').createSitemap();
```

**Comment by TriPSs** [comment]
Aah, I did not know that, created an API now that generates it if the file does not exist.

**Comment by boazpoolman** [comment]
See the docs here: https://docs.strapi.io/developer-docs/latest/developer-resources/plugin-api-reference/admin-panel.html#bootstrap

**Comment by TriPSs** [comment]
Thanks! Then this ticket can be closed as this would do exactly what I need.

**Comment by boazpoolman** [comment]
Great :)
Do let me know if it works out for you.
If not I might add this as a feature

**Comment by TriPSs** [comment]
Currently have this:
```
export default {
  config: {
    locales: []
  },
  async bootstrap({ strapi }) {
    await strapi.plugin('sitemap').service('core').createSitemap()
  }
}
```

But it does not work, I think this is because it's ran on the client side when going to the admin panel.

**Comment by boazpoolman** [comment]
You are right. Pardon me. My bad. There is documentation about the server bootstrap phase.
Right here: https://docs.strapi.io/developer-docs/latest/setup-deployment-guides/configurations/optional/functions.html#bootstrap

**Comment by TriPSs** [comment]
Yes that seems to work 🎉 

My file now:
```
export default {
  /**
   * An asynchronous register function that runs before
   * your application is initialized.
   *
   * This gives you an opportunity to extend code.
   */
  register(/*{ strapi }*/) {},

  /**
   * An asynchronous bootstrap function that runs before
   * your application gets started.
   *
   * This gives you an opportunity to set up your data model,
   * run jobs, or perform some special logic.
   */
  async bootstrap({ strapi }) {
    await strapi.plugin('sitemap').service('core').createSitemap();
  },
};
```
