### ISSUE TITLE
beta version generates sitemap each get request to strapi

### ISSUE THREAD

**Issue by dimasxp** [boazpoolman/strapi-plugin-sitemap#95]
### Describe the bug
generates sitemap file each get request to strapi. this is bug ? or how to switch off it? thanks
I'm using beta version. 

### Screenshots
![CleanShot 2022-10-06 at 04 04 14@2x](https://user-images.githubusercontent.com/7904186/194191308-b91d3e4a-978a-49b6-a711-32b0601ef552.jpg)

### System

- Node.js version:  Node LTS 
- Strapi version:4.4.3

**Comment by boazpoolman** [comment]
That doesn’t seem right. Let me see if I can reproduce the issue

**Comment by dimasxp** [comment]
oh, seems I understood the problem, in my findOne I get some data from an external API and automatically update the found entity. basically after each update sitemap is re-generated?

**Comment by boazpoolman** [comment]
I'm gonna close this as it's not per se an issue with this plugin, but rather an issue with the implementation.

Please feel free to re-open this issue if you still have any questions.
