### ISSUE TITLE
JSON output support

### ISSUE THREAD

**Issue by multipliedtwice** [boazpoolman/strapi-plugin-sitemap#96]
### Summary

Hello, thank you for an amazing plugin. I have a question - is there any way to get JSON output without XML?

### Why is it needed?

Because the frontend side has a different domain name and few frontend-specific routes, such as `/terms`, `privacy`, `sign in`, etc

### Suggested solution(s)

JSON output with pagination support for split-sitemaps

**Comment by boazpoolman** [comment]
Hey @thousandsofraccoons,

Thanks for the feature request.
Seems like a good suggestion.
I don't have the time to implement this feature just yet but I'll leave it open for in the future.

**Comment by boazpoolman** [comment]
I've decided not to implement this feature. Sorry.
