### ISSUE TITLE
[Question] Single collection type

### ISSUE THREAD

**Issue by kwiat1990** [boazpoolman/strapi-plugin-sitemap#98]
Hey, I use version `2.0.8` of this package and I wonder if there is a way to add a single collection type under URL bundles? For example, right know I can't add something like "about", which is a single page/single collection type, with the URL `/about`. 

The only solution seems to add it under "custom URLs" or am I missing something?

**Comment by timshinsergey** [comment]
A similar question for multilingual

Different languages have the same slug, but I can't add it

![image](https://user-images.githubusercontent.com/33506866/212061284-b86a8018-aefc-4039-9e42-de1fa055c976.png)

**Comment by yevhenskakun** [comment]
Try it: `/[locale]/contacts`

**Comment by boazpoolman** [comment]
Hmm. But why wouldn't you just make a custom URL for this page?
Seeing as it doesn't have any dynamic values in it. Makes perfect sense to me.

**Comment by boazpoolman** [comment]
I recommend adding a custom URL for single pages that don't have a dynamic URL.

I'm gonna close this due to inactivity.
